<template>
  <div>
    <section class="hero is-large hero-city">
      <div class="hero-body">
        <p class="subtitle">BIOHITECH</p>
        <h1 class="title is-size-1-desktop">Municipal Solid Waste</h1>
        <nuxt-link class="button is-light is-outlined" to="/contact">Contact Us to Learn More&nbsp;&nbsp;&nbsp;&nbsp;
          <b-icon icon="arrow-right" size="is-small"/>
        </nuxt-link>
      </div>
    </section>

    <section class="section has-background-light">
      <div class="container">
        <div class="columns">
          <div class="column">
            <p class="subtitle">LANDFILL REDUCTION</p>

            <h2 class="title">Cities are Getting Greener</h2>
            <p>Municipal solid waste (MSW) is waste generated by households and non-hazardous commercial waste such as
              food, paper, textile, plastic, metal, garden waste, batteries, and electronic gadgets. The Environmental
              Protection Agency estimates that there was an increase of solid waste generated in the U.S. from 262.1
              million tons in 2015 to 267.8 million tons in 2017.</p>

            <p>Managing municipal waste continues to be a challenge for urban areas across the U.S. because many items
              that can be refurbished or given to others in need end up in landfills. Many gadgets with recyclable parts
              are packed into landfills as garbage while food waste rots away as well.</p>

            <p>Proper waste management is essential for building sustainable cities. The World Bank estimates that
              managing solid waste is expensive for most cities, accounting for 20% to 50% of most municipal budgets.
              City waste management requires sustainable, efficient, and socially supported systems.</p>
          </div>
          <div class="column is-offset-1-desktop is-4">
            <figure class="image is-4by5"><img loading="lazy" src="/img/handful-of-dort-4by5.jpg"
                                               alt="Photo of Handful of Dirt"></figure>
          </div>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container">
        <div class="columns is-multiline">
          <div class="column is-full has-text-centered">
            <h2 class="title">
              BioHiTech Benefits
            </h2>

            <p class="has-text-centered">We are committed to solutions that have a positive environmental impact.</p>
          </div>
          <div class="column">
            <p><strong>Economic Benefits of Sustainability in Waste Management</strong></p>
            <p>Waste management includes everything from collection, sorting, and transportation to final treatment and
              disposal. It also involves activities like recycling and recovery.</p>

            <p>Adopting sustainable ideas for cities concerning waste management can deliver substantial economic
              benefits. Some of these include reducing water and air pollution, cutting fuel costs, reducing the amount
              of land used for landfills, achieving zero-waste initiatives, and minimizing greenhouse gas emissions.</p>

            <p>Sustainable waste management can provide a source of energy and create renewable resources. It can also
              create new jobs, especially when new waste-to-energy plants are built. Moreover, sustainable management of
              waste can reduce the cost of healthcare and make delivering healthcare more sustainable by reducing
              pollution, providing better locally grown produce, and preventing a wide range of diseases.</p>

            <p>When communities work together to reduce and manage waste efficiently, they reap multiple benefits,
              including improving the financial health of local government agencies along with the economic prosperity
              of residents and their businesses.</p>

            <p>Residents and local businesses generate savings by reducing their expenses on energy, gas, water,
              electricity and waste disposal. Communities with well-organized waste management systems can attract
              domestic and international businesses and increase the migration of middle- and high-income earners.</p>

          </div>
          <div class="column">
            <p><strong>What Municipality Waste Management Solutions Does BioHiTech Global Offer?</strong></p>
            <p>BioHiTech Global provides a proven and patented technology that helps municipalities and corporations
              achieve their zero-waste initiatives. Our food waste digester uses mechanical and biological technology to
              eliminate the need to take food waste to the landfill. This reduces the emission of methane at landfill
              sites.</p>

            <p>MSW landfills are the third-highest producers of human-related methane emissions. Methane accounts for
              more environmental damage than carbon dioxide. It has 28 to 36 times more capacity to trap heat in the
              atmosphere than carbon dioxide. Landfills accounted for over 14% of the emission of methane in 2017,
              according to statistics provided by the EPA.</p>

            <p>Our facility in Martinsburg, WV, known as Entsorga West Virginia, LLC, also deploys robust fuel
              production technology. This cost-effective solution handles all types of solid waste, extracting
              recyclable materials and turning the other parts into solid fuel pellets. These pellets are currently
              being used by Argos US, a cement manufacturing company, as a replacement for coal in their cement
              kiln.</p>
          </div>
        </div>
        <div class="column is-full">
          <nuxt-link class="button is-primary" to="/contact">CALL FOR A DEMO</nuxt-link>
          <a class="button is-primary" href="http://investors.biohitechglobal.com/">VISIT OUR INVESTOR PAGE</a>
        </div>
      </div>
    </section>

    <meta-tags title="Cities are Getting Greener | Municipal Waste & BioHiTech" description="The EPA estimates that there was an increase of solid waste generated in the U.S. from 262.1 million tons in 2015 to 267.8 million tons in 2017."/>
  </div>
</template>

<script>
  export default {
    name: "restaurants",
  }
</script>

